### ISSUE TITLE
enrichment  probleme

### ISSUE THREAD

**Issue by alienn233** [isaisg/gfobap#3]
hi,Isai!
could you can offer "matrix_Xanthomonadaceae_cog.tsv"?and  What is the analytical method for this?(Could you give me the detailed steps?) 
Best wishes to you ：）
I hope you write to me soon!

**Comment by isaisg** [comment]
Hello,
In the previous  issue I uploaded a test matrix to  test the enrichment workflow. 
In the article we computed the enrichment profiles using two types of tests, phylogeny unaware and aware tests. The unaware test we used was a hypergeometric test of enrichment, we used two forms of it, binary and raw counts, the binary version takes into account only presence or absence of an orthogroup in a genome, in opposition the raw counts take into account copy number of an orthogroup in a genome.
The phylogenetic aware tests we used are the phylogenetic logistic regression implemented in phylolm, again we used two forms of input matrix for this test, binary and raw counts. The idea behind the phylogenetic logistic regression is to control for the related nature of the samples (genomes) by estimating the correlation between genomes using a phylogenetic tree and correcting for this correlation structure. Check the following reference for more details
https://www.ncbi.nlm.nih.gov/pubmed/20525617
Finally we used scoary that implements the pairwise comparison algorithm to find orthogroups enriched or depleted widely across a given phylogeny.
The core 3 inputs for the worflow are: a matrix of orthogroups across genomes, a table in which each genome is assigned a label (e.g in our case PA or NPA), finally a phylogenetic tree for all genomes analyzed.
The pipeline implemented in oh.wrapper_enrichment.sh is a summary of the workflow we utilized, the sole intention of it is to show the required inputs by each test as well as parameters used to compute the tests. Because the high number of genomes in our study, we parallelized most part of the workflow in a computer cluster.
Isai
