### ISSUE TITLE
oh.bugwas.R

### ISSUE THREAD

**Issue by yangfanLiu1995** [isaisg/gfobap#4]
Hi:
I found that you used the R package "bugwas" in the  enrichment module.But in your article,this approach is not showed.

So what's the role of "bugwas"?

Look forward to your reply.

Yangfan
2019.3.8

**Comment by isaisg** [comment]
Hello Yangfan,
During the development of the project we tested different methodologies to compute the enrichment including bugwas. In the original bugwas article the authors benchmarked their pipeline in a context very different from our dataset, the genomes they utilized belonged to the single species level. Because in our dataset we had high divergence of genomes (multiples families across one single group of genomes contrasted) we decided to use the pairwise comparison algorithm implementd in scoary instead.
I included the bugwas code as a test  code  in case someone wanted to  run bugwas in their particular dataset.
Thanks
Isai

**Comment by yangfanLiu1995** [comment]
I understand now.

Thank you
